"""Add release_date to Album

Revision ID: 5394ec235d27
Revises: f27f678a6c0f
Create Date: 2025-01-20 12:31:18.712736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5394ec235d27'
down_revision = 'f27f678a6c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_albums_artist_id_artists'), 'artists', ['artist_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_albums_artist_id_artists'), type_='foreignkey')
        batch_op.drop_column('release_date')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
