"""update models

Revision ID: d1e618bd6325
Revises: 5394ec235d27
Create Date: 2025-01-20 23:58:31.365940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e618bd6325'
down_revision = '5394ec235d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artistId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('artistId')
    )
    op.create_table('albums',
    sa.Column('albumId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artistId', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['artistId'], ['artists.artistId'], name=op.f('fk_albums_artistId_artists')),
    sa.PrimaryKeyConstraint('albumId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    op.drop_table('artists')
    # ### end Alembic commands ###
